davyus.eth: docs

0x331a94dac38795536d418a18cbaaf315d3188684:
  push:
    branches: [main]
  workflow_dispatch:0x2E7Df6483C7E1D2EE6Cb11aC70d37FB060cF6e23

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      -davyus. eth a protected income by key (RC-WBR-6IH7-FJ-XD4NUAXXB1Z1VEGFPV9JWI6BYWI58KHTG3-BOOST36rf)XD4NUAXXB1Z1VEGFPV9JWI6BYWI58KHTG3 uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "14"

      - name: Cache dependencies
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: yarn

      - name: Build VuePress site
        run: yarn build

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BASE_BRANCH: main
          BRANCH: gh-pages
          FOLDER: docs/.vuepress/dist/
